name = "favicon-du-dev"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# [routes]
# Run 'wrangler deploy --routes "example.com/ico*"' or configure in Dashboard
# routes = [
#   { pattern = "example.com/ico*", zone_name = "example.com" }
# ]

[observability]
enabled = true
