# ⚠️ 注意：此文件由部署脚本自动覆盖（wrangler-personal.toml 或 wrangler-demo.toml）
# 请直接修改上述对应的特定配置文件。

name = "demo-nav-du"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "NAV_CONFIG_KV"
id = "eda8d2c4a2a846dd8bdae2302df3c7d8"
